apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketball-stats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketball-stats
  template:
    metadata:
      labels:
        app: basketball-stats
    spec:
      containers:
        - image: lgaljo/rt_basketball_stats:latest
          name: basketball-stats
          env:
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com/mtcixuqz
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: mtcixuqz
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass-stats
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8086
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: basketball-stats
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      protocol: TCP
      targetPort: server
  selector:
    app: basketball-stats